<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: /Applications/XAMPP/xamppfiles/htdocs/collector/web-project/app/Presentation/@layout.latte */
final class Template_4018bf0f08 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">


	<title>';
		if ($this->hasBlock('title')) /* pos 8:9 */ {
			$this->renderBlock('title', [], function ($s, $type) {
				$ʟ_fi = new LR\FilterInfo($type);
				return LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('stripHtml', $ʟ_fi, $s));
			}) /* pos 8:22 */;
			echo ' | ';
		}
		echo 'Collector</title>

	<script src="';
		echo LR\HtmlHelpers::escapeAttr($basePath) /* pos 10:15 */;
		echo '/assets/main.js"></script>

	<style>
		body { font-family: Arial, sans-serif; margin: 1.5rem; }
		nav ul { display: flex; gap: 1rem; list-style: none; padding: 0; flex-wrap: wrap; }
		nav a { text-decoration: none; }
		table { border-collapse: collapse; width: 100%; }
		th, td { border: 1px solid #ddd; padding: .4rem; text-align: left; }
		.flash { padding: .5rem; background: #eff7ff; margin-bottom: .75rem; }
	</style>
</head>

<body>
<nav>
	<ul>
		<li><a href="';
		echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Home:default')) /* pos 25:10 */;
		echo '">Domů</a></li>
';
		if ($isTeacherRole) /* pos 26:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Teacher:Subjects:default')) /* pos 26:32 */;
			echo '">Učitel: témata</a></li>
';
		}
		if ($isTeacherRole) /* pos 27:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Teacher:Badges:default')) /* pos 27:32 */;
			echo '">Učitel: odznaky</a></li>
';
		}
		if ($isTeacherRole) /* pos 28:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Teacher:Collaboration:default')) /* pos 28:32 */;
			echo '">Učitel: spolupráce</a></li>
';
		}
		if ($isStudentRole) /* pos 29:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Student:Offers:default')) /* pos 29:32 */;
			echo '">Žák: pobídky</a></li>
';
		}
		if ($isStudentRole) /* pos 30:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Student:Profile:default')) /* pos 30:32 */;
			echo '">Žák: profil</a></li>
';
		}
		if (!$isLoggedIn) /* pos 31:7 */ {
			echo '		<li><a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Auth:Login:default')) /* pos 31:30 */;
			echo '">Přihlásit</a></li>
';
		}
		if ($isLoggedIn) /* pos 32:7 */ {
			echo '		<li>
			<strong>Role: ';
			echo LR\HtmlHelpers::escapeText($currentRole) /* pos 33:18 */;
			echo '</strong>
';
			if ($currentUserId !== null) /* pos 34:10 */ {
				echo '			<span> · účet #';
				echo LR\HtmlHelpers::escapeText($currentUserId) /* pos 34:53 */;
				echo '</span>
';
			}
			echo '			';
			if ($currentUserName !== null) /* pos 35:4 */ {
				echo '· <strong>Uživatel: ';
				echo LR\HtmlHelpers::escapeText($currentUserName) /* pos 35:56 */;
				echo '</strong>';
			}
			echo '
			· <a href="';
			echo LR\HtmlHelpers::escapeAttr($this->global->uiControl->link(':Auth:Login:logout')) /* pos 36:10 */;
			echo '">Odhlásit</a>

		</li>
';
		}
		echo '	</ul>
</nav>

';
		foreach ($flashes as $flash) /* pos 42:6 */ {
			echo '<div';
			echo ($ʟ_tmp = array_filter(['flash', $flash->type])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 42:37 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText($flash->message) /* pos 42:67 */;
			echo '</div>
';

		}

		echo "\n";
		$this->renderBlock('content', [], 'html') /* pos 44:1 */;
		echo '</body>
</html>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['flash' => '42'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
