<?php

/** Generated by Latte 3.1.1 */

use Latte\Runtime as LR;

/** source: /Applications/XAMPP/xamppfiles/htdocs/collector/web-project/app/Presentation/Home/default.latte */
final class Template_97c9459e0e extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('title', get_defined_vars()) /* pos 2:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['subject' => '13'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {block title} on line 2 */
	public function blockTitle(array $ʟ_args): void
	{
		echo 'Sbírej a uč se';
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<main>
	<h1>Sbírej a uč se</h1>
	<p>
		Každý krok se počítá – vyber si předmět, uč se pravidelně a sleduj, jak se tvoje znalosti každý den rozrůstají.
	</p>

	<h2>Předměty</h2>
';
		if ($subjects) /* pos 11:2 */ {
			echo '		<ul>
';
			foreach ($subjects as $subject) /* pos 13:8 */ {
				echo '			<li>
				';
				echo LR\HtmlHelpers::escapeText($subject->name ?? $subject->title ?? 'Předmět #' . ($subject->id ?? 'bez ID')) /* pos 14:5 */;
				echo '
			</li>
';

			}

			echo '		</ul>
';
		} else /* pos 17:2 */ {
			echo '		<p>Zatím nejsou k dispozici žádné předměty.</p>
';
		}
		echo '</main>
';
	}
}
